version: "3.8"

services:
  redis:
    image: redis:5.0.14-alpine3.16
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      # config
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      # backup
      - '/var/lib/redis:/data'
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
